runtime: nodejs20
service: mm-embed
instance_class: F2
default_expiration: '0s'

# handlers element provides a list of URL patterns and descriptions of how they should be handled.
# https://cloud.google.com/appengine/docs/standard/python/config/appref#handlers_element
handlers:
  - url: /static
    static_dir: static

  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto
